# --- Mundo y generación ---
level-name=world
gamemode=survival
difficulty=normal
hardcore=false
generate-structures=true
spawn-protection=0
max-world-size=29999984

# --- Rendimiento (clave para Create) ---
view-distance=8
simulation-distance=6
entity-broadcast-range-percentage=70
max-tick-time=-1
sync-chunk-writes=false
use-native-transport=true
network-compression-threshold=256

# --- Jugadores y acceso ---
max-players=20
online-mode=true
enforce-secure-profile=true
white-list=false
enforce-whitelist=false
pvp=true
allow-flight=false

# --- Comandos y consola ---
enable-command-block=true
op-permission-level=4
function-permission-level=2

# --- Red ---
server-port=25565
query.port=25565
enable-query=false
enable-rcon=false

# --- Otros ---
motd=Server Create: Ultimate Selection 2
allow-nether=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
